# Generated by Django 5.0.14 on 2025-10-13 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(help_text='Liste des adresses email destinataires')),
                ('subject', models.CharField(help_text="Sujet de l'email", max_length=500)),
                ('html_content', models.TextField(help_text="Contenu HTML complet de l'email")),
                ('plain_content', models.TextField(blank=True, help_text="Version texte de l'email")),
                ('from_email', models.CharField(help_text="Adresse d'expéditeur", max_length=255)),
                ('template_used', models.CharField(blank=True, help_text="Template utilisé pour générer l'email", max_length=255)),
                ('send_method', models.CharField(choices=[('mailgun', 'Mailgun'), ('smtp', 'SMTP')], help_text="Méthode d'envoi utilisée", max_length=50)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure d'envoi")),
                ('attachments_info', models.JSONField(blank=True, help_text='Informations sur les pièces jointes (noms de fichiers, types MIME)', null=True)),
                ('context_snapshot', models.JSONField(blank=True, help_text='Snapshot du contexte utilisé (excluant les données sensibles)', null=True)),
            ],
            options={
                'verbose_name': "Log d'email",
                'verbose_name_plural': "Logs d'emails",
                'db_table': 'admin_platform_email_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='admin_platf_sent_at_675740_idx'), models.Index(fields=['send_method'], name='admin_platf_send_me_a6c6ff_idx')],
            },
        ),
    ]
