# Generated by Django 5.2.4 on 2025-09-10 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_installation_alter_invoice_quote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['due_date', 'created_at'], 'verbose_name': 'Échéance', 'verbose_name_plural': 'Échéances'},
        ),
        migrations.RemoveField(
            model_name='installment',
            name='position',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
