# Generated by Django 5.0.14 on 2025-10-19 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_initial'),
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='uq_invoice_installation_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='custom_recipient_address',
            field=models.TextField(blank=True, help_text='Adresse complète du destinataire'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='custom_recipient_company',
            field=models.CharField(blank=True, help_text='Entreprise du destinataire', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='custom_recipient_name',
            field=models.CharField(blank=True, help_text='Nom du destinataire (facture standalone)', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='custom_recipient_siret',
            field=models.CharField(blank=True, help_text="SIRET de l'entreprise", max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='installations.form'),
        ),
    ]
