# Generated by Django 5.1.7 on 2025-08-19 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0004_prospectrequest_converted_to_offer_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('housing_type', models.CharField(blank=True, max_length=100)),
                ('project_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('to_contact', 'À contacter'), ('phone_meeting', 'Rendez-vous Téléphonique'), ('meeting', 'Rendez-vous physique/Visio'), ('quote_sent', 'Devis envoyé'), ('negotiation', 'Négociation/questions'), ('quote_signed', 'Devis signé')], default='to_contact', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='request.prospectrequest')),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'db_table': 'offers_offer',
                'ordering': ['-created_at'],
            },
        ),
    ]
