# Generated by Django 5.0.14 on 2025-10-13 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('project_details', models.TextField(blank=True)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('to_contact', 'À contacter'), ('phone_meeting', 'Rendez-vous Téléphonique'), ('meeting', 'Rendez-vous physique/Visio'), ('quote_sent', 'Devis envoyé'), ('negotiation', 'Négociation/questions'), ('quote_signed', 'Devis signé')], default='to_contact', max_length=20)),
                ('installation_moved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_to_request_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offre',
                'verbose_name_plural': 'Offres',
                'db_table': 'offers_offer',
                'ordering': ['-created_at'],
            },
        ),
    ]
