# Generated by Django 5.2.4 on 2025-08-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_offer_housing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='installation_moved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
