# Generated by Django 5.2.4 on 2025-08-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_installation_moved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='returned_to_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
