# Generated by Django 5.2.4 on 2025-09-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_returned_to_request_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
