version: '3.9'

services:
  web:
    build: .
    network_mode: "host"
    volumes:
      - .:/app
      - /home/root/EuropGreen-Solar/back/statics:/app/statics
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    network_mode: "host"
    environment:
      POSTGRES_DB: nomdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: motdepasse
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: