version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nomdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: motdepasse
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
