# Generated by Django 5.1.7 on 2025-08-15 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('housing_type', models.CharField(blank=True, max_length=100)),
                ('electricity_bill', models.FileField(blank=True, null=True, upload_to='requests/bills/')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('followup', 'À relancer'), ('info', 'Demande de renseignement'), ('in_progress', 'En cours'), ('closed', 'Clôturé')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('call_center', 'Call Center'), ('web_form', 'Formulaire de demande')], default='web_form', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'db_table': 'requests_prospect',
                'ordering': ['-created_at'],
            },
        ),
    ]
