# Generated by Django 5.0.14 on 2025-10-13 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('housing_type', models.CharField(blank=True, max_length=100)),
                ('electricity_bill', models.FileField(blank=True, null=True, upload_to='requests/bills/')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('followup', 'À relancer'), ('info', 'Demande de renseignement'), ('in_progress', 'En cours'), ('closed', 'Clôturé')], default='new', max_length=20)),
                ('source_type', models.CharField(choices=[('call_center', 'Call Center'), ('web_form', 'Formulaire de demande'), ('client', 'Client'), ('collaborator', 'Collaborateur'), ('commercial', 'Commercial')], default='web_form', max_length=20)),
                ('appointment_date', models.DateTimeField(null=True)),
                ('converted_to_offer_at', models.DateTimeField(blank=True, null=True)),
                ('converted_decision', models.BooleanField(blank=True, null=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('value', 'Valeur fixe')], default='value', help_text='Type de commission pour la source (collaborateur/client)', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, help_text='Valeur de la commission : pourcentage (ex: 15.50) ou montant fixe en euros', max_digits=10)),
                ('sales_commission_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('value', 'Valeur fixe')], default='value', help_text='Type de commission pour le commercial', max_length=20)),
                ('sales_commission_value', models.DecimalField(decimal_places=2, default=0, help_text='Valeur de la commission commerciale : pourcentage (ex: 15.50) ou montant fixe en euros', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'db_table': 'requests_prospect',
                'ordering': ['-created_at'],
            },
        ),
    ]
