# Generated by Django 5.2.4 on 2025-08-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospectrequest',
            name='notes',
        ),
    ]
