# Generated by Django 5.1.7 on 2025-08-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_prospectrequest_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectrequest',
            name='converted_to_offer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
