# Generated by Django 5.2.4 on 2025-09-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_prospectrequest_converted_to_offer_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectrequest',
            name='converted_decision',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
