# Generated by Django 5.2.4 on 2025-09-30 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_source_to_source_type(apps, schema_editor):
    """Copie les valeurs de source vers source_type avant la transformation"""
    ProspectRequest = apps.get_model('request', 'ProspectRequest')
    for obj in ProspectRequest.objects.all():
        obj.source_type = obj.source
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_prospectrequest_converted_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Ajouter source_type
        migrations.AddField(
            model_name='prospectrequest',
            name='source_type',
            field=models.CharField(choices=[('call_center', 'Call Center'), ('web_form', 'Formulaire de demande'), ('client', 'Client'), ('collaborator', 'Collaborateur')], default='web_form', max_length=20),
        ),
        # 2. Copier les données de source vers source_type
        migrations.RunPython(copy_source_to_source_type, migrations.RunPython.noop),
        # 3. Renommer l'ancien champ source en source_old
        migrations.RenameField(
            model_name='prospectrequest',
            old_name='source',
            new_name='source_old',
        ),
        # 4. Créer le nouveau champ source comme ForeignKey
        migrations.AddField(
            model_name='prospectrequest',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_sources', to=settings.AUTH_USER_MODEL),
        ),
        # 5. Supprimer l'ancien champ source_old
        migrations.RemoveField(
            model_name='prospectrequest',
            name='source_old',
        ),
    ]
