# Generated by Django 5.2.4 on 2025-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_prospectrequest_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectrequest',
            name='source_type',
            field=models.CharField(choices=[('call_center', 'Call Center'), ('web_form', 'Formulaire de demande'), ('client', 'Client'), ('collaborator', 'Collaborateur'), ('commercial', 'Commercial')], default='web_form', max_length=20),
        ),
    ]
