# Generated by Django 5.2.4 on 2025-10-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_alter_prospectrequest_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectrequest',
            name='commission_type',
            field=models.CharField(choices=[('percentage', 'Pourcentage'), ('value', 'Valeur fixe')], default='value', help_text='Type de commission pour la source (collaborateur/client)', max_length=20),
        ),
        migrations.AddField(
            model_name='prospectrequest',
            name='commission_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur de la commission : pourcentage (ex: 15.50) ou montant fixe en euros', max_digits=10),
        ),
        migrations.AddField(
            model_name='prospectrequest',
            name='sales_commission_type',
            field=models.CharField(choices=[('percentage', 'Pourcentage'), ('value', 'Valeur fixe')], default='value', help_text='Type de commission pour le commercial', max_length=20),
        ),
        migrations.AddField(
            model_name='prospectrequest',
            name='sales_commission_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valeur de la commission commerciale : pourcentage (ex: 15.50) ou montant fixe en euros', max_digits=10),
        ),
    ]
