# Generated by Django 5.0.14 on 2025-10-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_3days_sent',
            field=models.BooleanField(default=False, verbose_name='Rappel 3 jours envoyé'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_deadline_sent',
            field=models.BooleanField(default=False, verbose_name='Notification échéance envoyée'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_hours_sent',
            field=models.BooleanField(default=False, verbose_name='Rappel 3h envoyé'),
        ),
    ]
