# Generated by Django 5.0.14 on 2025-10-13 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('offers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='quote',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='billing.quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.quote'),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='source_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_lines', to='billing.product'),
        ),
        migrations.AddField(
            model_name='quotesignature',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='billing.quote'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('offer', 'version'), name='uq_quote_offer_version'),
        ),
    ]
