# Generated by Django 5.1.7 on 2025-08-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
