# Generated by Django 5.1.7 on 2025-08-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_quote_number_quoteline_discount_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='unit',
        ),
    ]
