# Generated by Django 5.2.4 on 2025-08-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_product_sku_remove_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='quotes/pdfs/'),
        ),
    ]
