# Generated by Django 5.2.4 on 2025-08-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_quote_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteline',
            options={'ordering': ['created_at'], 'verbose_name': 'Ligne de devis', 'verbose_name_plural': 'Lignes de devis'},
        ),
        migrations.RemoveField(
            model_name='quoteline',
            name='position',
        ),
    ]
