# Generated by Django 5.2.4 on 2025-08-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_quoteline_options_remove_quoteline_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteline',
            options={'verbose_name': 'Ligne de devis', 'verbose_name_plural': 'Lignes de devis'},
        ),
    ]
