# Generated by Django 5.2.4 on 2025-08-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_quoteline_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteline',
            options={'ordering': ['position', 'created_at'], 'verbose_name': 'Ligne de devis', 'verbose_name_plural': 'Lignes de devis'},
        ),
        migrations.AddField(
            model_name='quoteline',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
