# Generated by Django 5.2.4 on 2025-08-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_quoteline_options_quoteline_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotesignature',
            name='signature_data',
        ),
        migrations.RemoveField(
            model_name='quotesignature',
            name='signer_email',
        ),
    ]
