# Generated by Django 5.2.4 on 2025-08-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_quotesignature_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='negociations',
            field=models.TextField(blank=True),
        ),
    ]
