# Generated by Django 5.2.4 on 2025-09-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_quote_negociations'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de commission calculé à la signature', max_digits=12),
        ),
    ]
