# Generated by Django 5.2.4 on 2025-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_quote_commission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sales_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de commission du commercial (assigned_to)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='quote',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de commission du collaborateur/client (source)', max_digits=12),
        ),
    ]
