# Generated by Django 5.2.4 on 2025-08-21 00:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0002_remove_offer_housing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_first_name', models.CharField(max_length=100)),
                ('client_last_name', models.CharField(max_length=100)),
                ('client_address', models.TextField()),
                ('installation_power', models.DecimalField(decimal_places=2, max_digits=5)),
                ('installation_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installations', to=settings.AUTH_USER_MODEL)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installations_form', to='offers.offer')),
            ],
            options={
                'verbose_name': "Fiche d'installation",
                'verbose_name_plural': "Fiches d'installation",
                'db_table': 'installations_form',
                'ordering': ['-created_at'],
            },
        ),
    ]
