# Generated by Django 5.0.14 on 2025-10-13 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
        ('offers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativevalidation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_administrative_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissioning',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commissionings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consuelvisit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consuel_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enedisconnection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enedis_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='affected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installations_form', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='enedisconnection',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enedis_connection', to='installations.form'),
        ),
        migrations.AddField(
            model_name='consuelvisit',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consuel_visit', to='installations.form'),
        ),
        migrations.AddField(
            model_name='commissioning',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commissioning', to='installations.form'),
        ),
        migrations.AddField(
            model_name='administrativevalidation',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_validation', to='installations.form'),
        ),
        migrations.AddField(
            model_name='installationcompleted',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_installation_completeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installationcompleted',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_completed', to='installations.form'),
        ),
        migrations.AddField(
            model_name='representationmandate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_representation_mandates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='representationmandate',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representation_mandate', to='installations.form'),
        ),
        migrations.AddField(
            model_name='representationmandate',
            name='client_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representation_mandate_client', to='installations.signature'),
        ),
        migrations.AddField(
            model_name='representationmandate',
            name='installer_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representation_mandate_installer', to='installations.signature'),
        ),
        migrations.AddField(
            model_name='installationcompleted',
            name='client_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_completed_client', to='installations.signature'),
        ),
        migrations.AddField(
            model_name='installationcompleted',
            name='installer_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_completed_installer', to='installations.signature'),
        ),
        migrations.AddField(
            model_name='technicalvisit',
            name='client_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_visit_client', to='installations.signature'),
        ),
        migrations.AddField(
            model_name='technicalvisit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_technical_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicalvisit',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_visit', to='installations.form'),
        ),
        migrations.AddField(
            model_name='technicalvisit',
            name='installer_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_visit_installer', to='installations.signature'),
        ),
    ]
