# Generated by Django 5.2.4 on 2025-08-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_form_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalvisit',
            name='additional_equipment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
