# Generated by Django 5.2.4 on 2025-09-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0004_alter_technicalvisit_additional_equipment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationcompleted',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='installations/completed/reports/'),
        ),
    ]
