# Generated by Django 5.2.4 on 2025-09-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0006_form_affected_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='client_first_name',
        ),
        migrations.RemoveField(
            model_name='form',
            name='client_last_name',
        ),
    ]
