# Generated by Django 5.2.4 on 2025-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0007_remove_form_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Commission du collaborateur/client (apporteur d'affaires)", max_digits=12),
        ),
        migrations.AddField(
            model_name='form',
            name='commission_paid',
            field=models.BooleanField(default=False, help_text='Indique si la commission du collaborateur/client a été payée'),
        ),
        migrations.AddField(
            model_name='form',
            name='sales_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission du commercial (assigned_to)', max_digits=12),
        ),
        migrations.AddField(
            model_name='form',
            name='sales_commission_paid',
            field=models.BooleanField(default=False, help_text='Indique si la commission du commercial a été payée'),
        ),
    ]
