# Generated by Django 5.0.14 on 2025-10-13 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0001_initial'),
        ('installations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfa16702',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cerfa16702', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='declarant_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cerfa16702_declarant', to='installations.signature'),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cerfa16702', to='installations.form'),
        ),
        migrations.AddField(
            model_name='cerfa16702attachment',
            name='cerfa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='administrative.cerfa16702'),
        ),
        migrations.AddField(
            model_name='consuel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consuels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consuel',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consuels', to='installations.form'),
        ),
        migrations.AddField(
            model_name='consuel',
            name='installer_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consuel_installer', to='installations.signature'),
        ),
        migrations.AddField(
            model_name='electricaldiagram',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_electrical_diagrams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='electricaldiagram',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_diagram', to='installations.form'),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='client_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enedis_mandate_client', to='installations.signature'),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enedis_mandates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enedis_mandate', to='installations.form'),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='installer_signature',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enedis_mandate_installer', to='installations.signature'),
        ),
        migrations.AddIndex(
            model_name='cerfa16702attachment',
            index=models.Index(fields=['cerfa', 'dpc_key', 'ordering'], name='administrat_cerfa_i_34c623_idx'),
        ),
        migrations.AddConstraint(
            model_name='cerfa16702attachment',
            constraint=models.UniqueConstraint(fields=('cerfa', 'dpc_key', 'ordering'), name='uniq_cerfa_dpc_ordering'),
        ),
    ]
