# Generated by Django 5.2.4 on 2025-08-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfa16702',
            name='company_denomination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='company_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='company_siret',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
