# Generated by Django 5.0.14 on 2025-11-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerfa16702',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_number_p2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_number_p3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_prefix_p2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_prefix_p3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_section',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_section_p2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='cadastral_section_p3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='land_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
