# Generated by Django 5.2.4 on 2025-08-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_cerfa16702_company_denomination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfa16702',
            name='company_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
