# Generated by Django 5.2.4 on 2025-08-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0003_cerfa16702_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enedismandate',
            name='client_address_locality',
        ),
        migrations.RemoveField(
            model_name='enedismandate',
            name='client_address_number',
        ),
        migrations.RemoveField(
            model_name='enedismandate',
            name='client_address_postal_code',
        ),
        migrations.RemoveField(
            model_name='enedismandate',
            name='client_address_street',
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc1',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc1/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc11',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc11/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc2',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc2/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc3',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc3/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc4',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc4/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc5',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc5/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc6',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc6/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc7',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc7/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc8',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/dpc8/'),
        ),
    ]
