# Generated by Django 5.2.4 on 2025-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_remove_enedismandate_client_address_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfa16702',
            name='cadastral_number_p2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='cadastral_number_p3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='cadastral_prefix_p2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='cadastral_prefix_p3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='cadastral_section_p2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='cadastral_section_p3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='cadastral_surface_m2_p2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cerfa16702',
            name='cadastral_surface_m2_p3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
