# Generated by Django 5.2.4 on 2025-09-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_cerfa16702_cadastral_number_p2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerfa16702',
            name='attachements_pdf',
            field=models.FileField(blank=True, null=True, upload_to='administrative/cerfa16702/attachements_pdfs/'),
        ),
        migrations.AlterField(
            model_name='cerfa16702',
            name='dpc11_notice_materiaux',
            field=models.TextField(blank=True, null=True),
        ),
    ]
