# Generated by Django 5.2.4 on 2025-09-12 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0006_cerfa16702_attachements_pdf_and_more'),
        ('installations', '0005_installationcompleted_report_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consuel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('144a', 'SC-144A'), ('144b', 'SC-144B'), ('144c', 'SC-144C'), ('144c2', 'SC-144C2')], default='144a', max_length=10)),
                ('number', models.CharField(blank=True, max_length=32, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='administrative/consuels/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consuels', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consuels', to='installations.form')),
                ('installer_signature', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consuel_installer', to='installations.signature')),
            ],
            options={
                'verbose_name': 'Consuel',
                'verbose_name_plural': 'Consuels',
                'db_table': 'administrative_consuel',
                'ordering': ['-created_at'],
            },
        ),
    ]
