# Generated by Django 5.2.4 on 2025-09-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0007_consuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enedismandate',
            old_name='client_company_represented_by',
            new_name='client_company_represented_by_name',
        ),
        migrations.RenameField(
            model_name='enedismandate',
            old_name='contractor_represented_by_name',
            new_name='contractor_company_represented_by_name',
        ),
        migrations.RenameField(
            model_name='enedismandate',
            old_name='contractor_represented_by_role',
            new_name='contractor_company_represented_by_role',
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='client_company_represented_by_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='contractor_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='contractor_civility',
            field=models.CharField(blank=True, choices=[('mr', 'Monsieur'), ('mme', 'Madame')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='contractor_type',
            field=models.CharField(choices=[('individual', 'Particulier'), ('company', 'La société'), ('collectivity', 'Collectivité')], default='individual', max_length=20),
        ),
    ]
