# Generated by Django 5.2.4 on 2025-09-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0008_rename_client_company_represented_by_enedismandate_client_company_represented_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enedismandate',
            name='client_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enedismandate',
            name='installer_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
