# Generated by Django 5.2.4 on 2025-09-26 15:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0009_enedismandate_client_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerfa16702Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dpc_key', models.CharField(choices=[('dpc1', 'DPC1'), ('dpc2', 'DPC2'), ('dpc3', 'DPC3'), ('dpc4', 'DPC4'), ('dpc5', 'DPC5'), ('dpc6', 'DPC6'), ('dpc7', 'DPC7'), ('dpc8', 'DPC8'), ('dpc11', 'DPC11')], max_length=10)),
                ('file', models.FileField(upload_to='administrative/cerfa16702/attachments/%Y/%m/%d/')),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cerfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='administrative.cerfa16702')),
            ],
            options={
                'verbose_name': 'Pièce jointe CERFA 16702',
                'verbose_name_plural': 'Pièces jointes CERFA 16702',
                'db_table': 'administrative_cerfa16702_attachment',
                'ordering': ['cerfa', 'dpc_key', 'ordering', 'created_at'],
                'indexes': [models.Index(fields=['cerfa', 'dpc_key', 'ordering'], name='administrat_cerfa_i_34c623_idx')],
                'constraints': [models.UniqueConstraint(fields=('cerfa', 'dpc_key', 'ordering'), name='uniq_cerfa_dpc_ordering')],
            },
        ),
    ]
