# Generated by Django 5.2.4 on 2025-09-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0011_populate_cerfa16702_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc1',
        ),
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc11',
        ),
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc2',
        ),
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc3',
        ),
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc4',
        ),
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc5',
        ),
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc6',
        ),
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc7',
        ),
        migrations.RemoveField(
            model_name='cerfa16702',
            name='dpc8',
        ),
    ]
