# Generated by Django 5.2.4 on 2025-08-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccess_accept_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccess',
            name='accept_invitation',
        ),
        migrations.AddField(
            model_name='user',
            name='accept_invitation',
            field=models.BooleanField(default=False),
        ),
    ]
