# Generated by Django 5.2.4 on 2025-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('installer', 'Installer'), ('secretary', 'Secretary'), ('regional_manager', 'Regional Manager'), ('customer', 'Customer'), ('admin', 'Administrateur')], default='employee', max_length=17),
        ),
    ]
