# Generated by Django 5.2.4 on 2025-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_phone_number_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('customer', 'Client'), ('collaborator', 'Collaborateur'), ('sales', 'Commercial')], default='collaborator', max_length=17),
        ),
    ]
