# Generated by Django 5.2.4 on 2025-09-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('customer', 'Client'), ('collaborator', 'Collaborateur'), ('sales', 'Commercial')], default='collaborator', max_length=20),
        ),
    ]
