# Generated by Django 5.2.4 on 2025-09-30 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commission', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('percentage', 'Pourcentage'), ('value', 'Valeur fixe')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Pourcentage (ex: 15.50) ou valeur fixe en euros', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'db_table': 'users_commission',
            },
        ),
    ]
