# Generated by Django 5.2.4 on 2025-10-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_commission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
